Zuul: [mediawiki/extensions/WikimediaCustomizations] Add EventStreamConfig dep
WikimediaCustomizations CI fails on
Error: A dependency error was encountered while installing the extension
"TestKitchen": Could not find the registration file for the extension "EventStreamConfig"

In Ic8c00aac4b88eb10aa66c1df2835101e0c0716a3 we added TestKitchen extension
but because the dependncies are not installed recursively, it fails with
missing EventStreamConfig extension. To fix the CI we need to define
EventStreamConfig as one of dependencies for WikimediaCustomization
extension.

Change-Id: I4ba8a38219c6d68fc228f1904a9923f55aaac458