utils: Use tox in docker-updates to avoid ModuleNotFoundError
Rather than requiring a global installation of python-debian
(which is undocumented and may conflict with other global tools,
and is disallowed by default when using Python from Homebrew),

... use the virtualenv that we already use for other python scripts
in this repo, so that dependencies are explicit and just work.

```
$ ./utils/docker-updates.py
Traceback (most recent call last):
  File "wikimedia-integration-config/./utils/docker-updates.py", line 10
    from debian.changelog import Changelog
ModuleNotFoundError: No module named 'debian'
```

Change-Id: I09a2e6a2be390c16541e17e59c0c3b69f0ef6d6d