Zuul: [mediawiki/extensions/PDFCreator] Add VueJsPlus dependency
The extension PDFCreator depends on extension VueJsPlus because it uses
the PHP class MediaWiki\Extension\VueJsPlus\Module\VueJsPlusModule.

https://integration.wikimedia.org/ci/job/quibble-composer-mysql-php81/9513/artifact/log/mw-error.log
reports:
Error: Class "MediaWiki\Extension\VueJsPlus\Module\VueJsPlusModule" not found

Change-Id: I7d83890de87e352c845107fd77139db93178999d