Revert "Docker: Drop node14 images, all now unused"
This reverts commit bb6aa8feb6439f61697cc0eb2f7cf893fcc9e503.

Reason for revert:

We had to kept the Selenium jobs to node14 due to wdio / fibers
Iabbb1ff3020e4511696187b227d974b08bb96794

  $ ./utils/docker-updates
  jjb/job-templates.yaml:670
  ERROR: docker-registry.wikimedia.org/releng/node14-test-browser not found!

Bug: T330426
Change-Id: I4b2623ed299f75c5631a13a7e47474d1bd8f0630