dockerfiles: fix update-alternatives for java8
The java package installation fails due to update-alternatives:

using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide
/usr/bin/rmid (rmid) in auto mode

error: error creating symbolic link
'/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory

The same issue occured in the openjdk8 production image.

No changelog bump since the image and its child failed to build.

Bug: T291425
Change-Id: Ic4e5a7c40b29a64d012d79cd0a541ba9c0c354eb