zuul: change OpenStack secret
Dan updated the WMCS Swift secrets with 9a5448963, the comment mentions
it is using access rules.  The upload-logs-swift still fail though.

openstack.exceptions.HttpException: HttpException:
401: Client Error for url: https://object.eqiad1.wikimediacloud.org
/swift/v1/AUTH_c26d9d326bdf464fa1025939ded7e5a2/artifacts,
Unauthorized

Last year I created an application credential with access rules
(35fad95fac) which did not work. I went to create a new one WITHOUT
access rule (7581396607).

After speaking with Andrew Boggot about it, there is a role
`object_storage` that restricts the user to that sole service. It still
grant access to any container, but that is at least a start until we can
figure out the rules.
We should also use a service account instead of a credential attached to
an individua. But that is a start!

This adds an application credential I have generated with
`object_storage` rule and now ACL.  That would let us validate the role
work.

Switch wmcs_cloud_config secret to that new credential.

Bug: T430479
Change-Id: If4dd08de9b6405fc58aae0c30fcdfd5d88ea15e5